### ISSUE TITLE
Build failed for --flavor=sdl-hercules

### ISSUE THREAD

**Issue by JamesWekel** [wrljet/hercules-helper#44]
On a Raspberry Pi 5, I attempted to build Sdl Hercules Develop branch with the current hercules-helper script.
```
tn529@ArmDev5:~$ git clone https://github.com/wrljet/hercules-helper.git
Cloning into 'hercules-helper'...
remote: Enumerating objects: 1525, done.
remote: Counting objects: 100% (216/216), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 1525 (delta 142), reused 191 (delta 124), pack-reused 1309 (from 1)
Receiving objects: 100% (1525/1525), 1.39 MiB | 10.31 MiB/s, done.
Resolving deltas: 100% (1003/1003), done.
tn529@ArmDev5:~$ mkdir dev/helper-develop
tn529@ArmDev5:~$ cd dev/helper-develop/
tn529@ArmDev5:~/dev/helper-develop$ ~/hercules-helper/hercules-buildall.sh --flavor=sdl-hercules
Using logfile: hercules-buildall-2024-09-05.log
```

but the build failed with:
```
  CCLD     libhercs.la
/usr/bin/ld: cannot find -lcrypto64: No such file or directory
/usr/bin/ld: cannot find -ldecNumber64: No such file or directory
/usr/bin/ld: cannot find -lSoftFloat64: No such file or directory
/usr/bin/ld: cannot find -ltelnet64: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:2254: libhercs.la] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/devstor/helper-develop/hyperion/build'
make[1]: *** [Makefile:2689: all-recursive] Error 1
make[1]: Leaving directory '/devstor/helper-develop/hyperion/build'
make: *** [Makefile:2007: all] Error 2

real    2m33.409s
user    8m2.444s
sys     0m54.510s
[[ error: ]] Make failed!
finish() called, exit status = 1
```

Here are the log files:
[hercules-buildall-2024-09-05.log](https://github.com/user-attachments/files/16899131/hercules-buildall-2024-09-05.log)
[extra-info-2024-09-05.log](https://github.com/user-attachments/files/16899137/extra-info-2024-09-05.log)
[build-commands-2024-09-05.log](https://github.com/user-attachments/files/16899139/build-commands-2024-09-05.log)

I suspect that SDL Hercules commits:
https://github.com/SDL-Hercules-390/hyperion/commit/9631b9271321599dbb189eca1c935238637a19c5
https://github.com/SDL-Hercules-390/hyperion/commit/1b955f4b035a0bb71fc712cd7b849d643c2a48e1
are related to the issue.

Thanks,
Jim

**Comment by wrljet** [comment]
Jim,

Yes, the recently-added mistake in SDL Hercules https://github.com/SDL-Hercules-390/hyperion/commit/1b955f4b035a0bb71fc712cd7b849d643c2a48e1 is causing your issue.

I'm working with Fish and Enrico now to get it corrected.  Should be checked in tomorrow I'd guess.

Bill

**Comment by wrljet** [comment]
Should now be fixed in SDL Hercules, by commit https://github.com/SDL-Hercules-390/hyperion/commit/30e4b08907fadc1add72ff3267b4958a01d76d48

Bill

**Comment by JamesWekel** [comment]
Bill,

On the Raspberry PI 5 (ARMBIAN JAMMY Linux), `~/hercules-helper/hercules-buildall.sh --flavor=sdl-hercules --auto` still fails:
```
 ~/hercules-helper/hercules-buildall.sh --flavor=sdl-hercules --auto
Using logfile: hercules-buildall-2024-09-09.log
Creating build cmds file: /home/tn529/dev/helper-develop/build-commands-2024-09-09.log
Creating extra diagnostic info file: /home/tn529/dev/helper-develop/extra-info-2024-09-09.log
Script version: /home/tn529/hercules-helper/hercules-buildall.sh: v0.9.14-115-gfc94cfb

Config file: /home/tn529/hercules-helper/sdl-hyperion.conf
```
with 
  ```
  CCLD     libhercs.la
  /usr/bin/ld: cannot find -lcrypto64: No such file or directory
  /usr/bin/ld: cannot find -ldecNumber64: No such file or directory
  /usr/bin/ld: cannot find -lSoftFloat64: No such file or directory
  /usr/bin/ld: cannot find -ltelnet64: No such file or directory
  collect2: error: ld returned 1 exit status
  make[2]: *** [Makefile:2254: libhercs.la] Error 1
  make[2]: *** Waiting for unfinished jobs....
  make[2]: Leaving directory '/devstor/helper-develop/hyperion/build'
  make[1]: *** [Makefile:2689: all-recursive] Error 1
  make[1]: Leaving directory '/devstor/helper-develop/hyperion/build'
  make: *** [Makefile:2007: all] Error 2
  
  real    2m33.728s
  user    8m6.126s
  sys     0m53.514s
  [[ error: ]] Make failed!
  finish() called, exit status = 1
```

Here are the logs:
[hercules-buildall-2024-09-09.log](https://github.com/user-attachments/files/16935359/hercules-buildall-2024-09-09.log)
[extra-info-2024-09-09.log](https://github.com/user-attachments/files/16935361/extra-info-2024-09-09.log)
[build-commands-2024-09-09.log](https://github.com/user-attachments/files/16935362/build-commands-2024-09-09.log)

Also I'm attaching ./hyperion/build/Makefile and 'make diagnostic'
[Makefile.txt](https://github.com/user-attachments/files/16935412/Makefile.txt)
[make.diagnostic.txt](https://github.com/user-attachments/files/16935414/make.diagnostic.txt)
to help analyzing the problem.

$LDFLAGS from the 'makefile diagnostics'  looks strange 
`$LDFLAGS            -Wl,--warn-common -L/home/tn529/dev/helper-develop/extpkgs/lib -L/home/tn529/dev/helper-develop/extpkgs/lib-L/home/tn529/dev/helper-develop/extpkgs/lib -L/home/tn529/dev/helper-develop/extpkgs/lib`

Missing a space between 2nd and 3rd -L parameters. In the Makefile, the 2nd parameter has a trailing '$'. 
To get a build, I have to update Makefile; add '/aarch64' to a -L parameter and remove the '$'.

Hope this helps,
Jim

**Comment by wrljet** [comment]
Fish must have goofed up the diff.

I'll rerun it here and yell at him.

**Comment by wrljet** [comment]
Jim,

OK, Fish forgot to run `autogen.sh` before checking all that in.  So the actual `configure` script is not the new one.

You can add `--autogen` to the Hercules-Helper command line and it'll do that step before running configure.

I've tested that here on a Pi 4.

Bill

**Comment by JamesWekel** [comment]
Bill,

With `--autogen`,  the install completed successfully!

Thank you for all your help and time,
Jim,

**Comment by wrljet** [comment]
You're very welcome!

Bill

**Comment by JamesWekel** [comment]
Bill,

I'm closing the issue as it has been resolved!

Jim
